[package]
name = "batl"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "The multi-repo development tool"
homepage = "https://github.com/lernib/batl"
repository = "https://github.com/lernib/batl"
readme = "README.md"
keywords = ["repository", "management", "battalion"]
categories = ["command-line-utilities", "development-tools", "filesystem"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
batl-macros = { version = "0.3.0", path = "../batl-macros" }
clap = { version = "4.5.53", features = ["derive"] }
color-eyre = "0.6.5"
colored = "3.0.0"
console = "0.16.2"
dialoguer = "0.12.0"
dirs = "6.0"
envfile = "0.2.1"
flate2 = "1.1.5"
git2 = "0.20.3"
ignore = "0.4.25"
pathdiff = "0.2.3"
rand = "0.9.2"
regex = "1.12.2"
semver = { version = "1.0.27", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.145"
tar = "0.4.44"
thiserror = "2.0.17"
toml = "0.9.10"
ureq = "3.1.4"
whoami = "1.6.1"
