[environment]
version = "0.3.0"

[repository]
name = "battalion.batl"
version = "0.1.0"

[scripts]
install = "cargo install --debug --path packages/batl"

[dependencies]
"battalion.batl.lambda" = "0.1.0"

[links]
"battalion.batl.lambda" = "extras/lambda"

[restrict.Unix]
include = "require"
